CREATE TABLE diabetes_data (	
SEQN FLOAT	NULLABLE,
age FLOAT	NULLABLE,
gender FLOAT	NULLABLE,
race FLOAT	NULLABLE,
income_ratio FLOAT	NULLABLE,
education_level FLOAT	NULLABLE,
weight_kg FLOAT	NULLABLE,
height_cm FLOAT	NULLABLE,
bmi FLOAT	NULLABLE,
waist_circumference_cm FLOAT	NULLABLE,
systolic_bp FLOAT	NULLABLE,
diastolic_bp FLOAT	NULLABLE,
total_cholesterol_si FLOAT	NULLABLE,
hdl_si FLOAT	NULLABLE,
log_acr FLOAT	NULLABLE,
smoker INTEGER	NULLABLE,
heavy_drinker INTEGER	NULLABLE,
liver_disease INTEGER	NULLABLE,
diabetes INTEGER	NULLABLE,
BMI_missingINTEGER	NULLABLE,
waist_missing INTEGER	NULLABLE,
glucose_missing INTEGER	NULLABLE
);